---
- name: Converge
  hosts: all
  connection: httpapi

  vars:
    ansible_host: "{{ lookup('env','F5_HOST') }}"
    ansible_user: "{{ lookup('env','F5_USER') }}"
    ansible_httpapi_password: "{{ lookup('env','F5_PASSWORD') }}"
    ansible_network_os: "f5networks.f5_bigip.bigip"
    ansible_httpapi_use_ssl: true
    ansible_httpapi_use_proxy: false
    ansible_httpapi_validate_certs: "{{ lookup('env','F5_VALIDATE_CERT') }}"
    ansible_httpapi_port: "{{ lookup('env','F5_SERVER_PORT') }}"
    f5_telemetry: false
    scenario_dir: "{{ lookup('env','MOLECULE_SCENARIO_DIRECTORY') }}"

  tags:
    - molecule-idempotence-notest

  collections:
    - f5networks.f5_bigip

  tasks:
    - include_tasks: tasks/main.yml
