---
scenario:
  name: default
  converge_sequence:
    - converge
  test_sequence:
    - create
    - lint
    - converge
    - destroy
  destroy_sequence:
    - destroy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-"sleep infinity"}
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      retry_files_enabled: false
      host_key_checking: false
  options:
    vvv: true
  log: true
  env:
    ANSIBLE_COLLECTIONS_PATHS: ${MOLECULE_PROJECT_DIRECTORY}/../../
