---

- name: Issue 01364 - Select users facts
  bigip_device_info:
    include:
      - users
  register: result

- name: Issue 01364 - Assert users facts
  assert:
    that:
      - result is success

- name: Issue 01364 - Create an admin user
  bigip_command:
    commands:
      - 'tmsh create auth user {{ username_credential }} password {{ password_credential }} partition-access add { all-partitions { role admin } } shell {{ shell }}'

- name: Issue 01364 - Select users facts
  bigip_device_info:
    include:
      - users
  register: result

- name: Issue 01364 - Assert users facts changed
  assert:
    that:
      - result is success
      - result.users | selectattr("name", "match", "johnd") | map(attribute='shell') | first == 'bash'

- name: Issue 01364 - Delete admin user
  bigip_command:
    commands:
      - 'tmsh create auth user {{ username_credential }}'