---
- name: Issue 01159 - Create test resources
  bigip_command:
    commands:
      - tmsh create ltm pool issue_01159_empty_one
      - tmsh create ltm node issue-01159-host address 1.1.1.1
      - 'tmsh create ltm pool issue_01159_not_empty_one members add { issue-01159-host:80 }'

- name: Issue 01159 - Collect Bigip pool facts
  bigip_device_info:
    gather_subset:
      - ltm-pools
  register: result

# add better asserts since we created pools

- name: Issue 01159 - Assert Bigip pool facts
  assert:
    that:
      - result is success

- name: Issue 01159 - Remove resources
  bigip_command:
    commands:
      - tmsh delete ltm pool issue_01159_empty_one
      - tmsh delete ltm pool issue_01159_not_empty_one
      - tmsh delete ltm node issue-01159-host