---
- name: Upload declaration
  bigip_ts_deploy:
    content: "{{ lookup('file', 'ts_declaration.json') }}"
  register: result

- name: Assert Upload declaration
  assert:
    that:
      - result is changed
      - result is success

- name: Upload declaration - Idempotent check
  bigip_ts_deploy:
    content: "{{ lookup('file', 'ts_declaration.json') }}"
  register: result

- name: Assert Upload declaration - Idempotent check
  assert:
    that:
      - result is not changed
      - result is success

- name: Upload declaration - force yes
  bigip_ts_deploy:
    content: "{{ lookup('file', 'ts_declaration.json') }}"
    force: yes
  register: result

- name: Assert Upload declaration - force yes
  assert:
    that:
      - result is changed
      - result is success

- name: Remove declaration
  bigip_ts_deploy:
    state: absent
  register: result

- name: Assert Remove declaration
  assert:
    that:
      - result is changed
      - result is success

- name: Remove declaration - Idempotent check
  bigip_ts_deploy:
    state: absent
  register: result

- name: Assert Remove declaration - Idempotent check
  assert:
    that:
      - result is not changed
      - result is success

# disabled this test due to https://github.com/F5Networks/f5-telemetry-streaming/issues/83, once its fixed we will test
#- name: Declaration produces errors
#  bigip_ts_deploy:
#    content: "{{ lookup('file', 'ts_failure.json') }}"
#  register: result
#  failed_when: result is success

#- name: Assert Declaration produces errors
#  assert:
#    that:
#      - result is not changed
#      - "'Unprocessable Entity' in result.msg"