---

- name: Declaration with 2 Tenants - AS3
  atc_deploy:
    content: "{{ lookup('file', 'two_tenants.json') }}"
    service_type: "as3"
  register: result

- name: Assert Declaration with 2 Tenants - AS3
  assert:
    that:
      - result is changed
      - result is success

- name: Declaration with 2 Tenants - AS3 - Idempotent check
  atc_deploy:
    content: "{{ lookup('file', 'two_tenants.json') }}"
    service_type: "as3"
  register: result

- name: Assert Declaration with 2 Tenants - AS3 - Idempotent check
  assert:
    that:
      - result is not changed
      - result is success

- name: Declaration change with 2 Tenants - AS3
  atc_deploy:
    content: "{{ lookup('file', 'two_tenants_changed.json') }}"
    service_type: "as3"
  register: result

- name: Assert Declaration change with 2 Tenants - AS3
  assert:
    that:
      - result is changed
      - result is success

- name: Declaration change with 2 Tenants - AS3 - Idempotent check
  atc_deploy:
    content: "{{ lookup('file', 'two_tenants_changed.json') }}"
    service_type: "as3"
  register: result

- name: Assert Declaration change with 2 Tenants - AS3 - Idempotent check
  assert:
    that:
      - result is not changed
      - result is success

- name: Remove one tenant - AS3
  atc_deploy:
    service_type: "as3"
    as3_tenant: "Sample_01"
    state: absent
  register: result

- name: Assert Remove one tenant - AS3
  assert:
    that:
      - result is changed
      - result is success

- name: Remove one tenant - AS3 - Idempotent check
  atc_deploy:
    service_type: "as3"
    as3_tenant: "Sample_01"
    state: absent
  register: result

- name: Assert Remove one tenant - AS3 - Idempotent check
  assert:
    that:
      - result is not changed
      - result is success

- name: Declaration with one tenant - AS3
  atc_deploy:
    content: "{{ lookup('file', 'one_tenant.json') }}"
    service_type: "as3"
  register: result

- name: Assert Declaration with one tenant - AS3
  assert:
    that:
      - result is changed
      - result is success

- name: Declaration with one tenant - AS3 - Idempotent check
  atc_deploy:
    content: "{{ lookup('file', 'one_tenant.json') }}"
    service_type: "as3"
  register: result

- name: Assert Declaration with one tenant - AS3 - Idempotent check
  assert:
    that:
      - result is not changed
      - result is success

- name: Remove all tenants - AS3
  atc_deploy:
    service_type: "as3"
    as3_tenant: "all"
    state: absent
  register: result

- name: Assert Remove all tenants - AS3
  assert:
    that:
      - result is changed
      - result is success

- name: Remove all tenants - AS3 - Idempotent check
  atc_deploy:
    service_type: "as3"
    as3_tenant: "all"
    state: absent
  register: result

- name: Assert Remove all tenants - AS3 - Idempotent check
  assert:
    that:
      - result is not changed
      - result is success

- name: Declaration produces errors - AS3
  atc_deploy:
    content: "{{ lookup('file', 'as3_produce_errors.json') }}"
    service_type: "as3"
  register: result
  failed_when: result is success

- name: Assert Declaration produces errors - AS3
  assert:
    that:
      - result is not changed
      - "'declaration is invalid' in result.msg"