---
- name: Upload declaration - TS
  atc_deploy:
    content: "{{ lookup('file', 'ts_declaration.json') }}"
    service_type: "ts"
  register: result

- name: Assert Upload declaration - TS
  assert:
    that:
      - result is changed
      - result is success

# module is not idempotent due to TS bug, these tests are just placeholders for when TS is fixed.
- name: Upload declaration - TS - Idempotent check
  atc_deploy:
    content: "{{ lookup('file', 'ts_declaration.json') }}"
    service_type: "ts"
  register: result

# module is not idempotent due to TS bug, these tests are just placeholders for when TS is fixed.
- name: Assert Upload declaration - TS - Idempotent check
  assert:
    that:
      - result is changed
      - result is success

- name: Declaration produces errors - TS
  atc_deploy:
    content: "{{ lookup('file', 'ts_failure.json') }}"
    service_type: "ts"
  register: result
  failed_when: result is success

- name: Assert Declaration produces errors - TS
  assert:
    that:
      - result is not changed
      - "'Unprocessable Entity' in result.msg"