---

# Test the bigip_regkey_pool module
#
# Running this playbook assumes that you have a BIG-IQ installation at the
# ready to receive the commands issued in this Playbook.
#
# This module will run tests against a BIG-IQ host to verify that the
# bigip_regkey_pool module behaves as expected.
#
# Usage:
#
#    ansible-playbook -i notahost, integration/bigiq_regkey_pool.yaml
#
# Examples:
#
#    Run all tests on the bigiq_regkey_pool module
#
#    ansible-playbook -i notahost, integration/bigip_regkey_pool.yaml
#

- name: Test the bigip_regkey_pool module
  hosts: "f5-bigiq[0]"
  connection: httpapi
  any_errors_fatal: true

  vars:
    ansible_user: "{{ lookup('env','F5_USER') }}"
    ansible_httpapi_password: "{{ lookup('env','F5_PASSWORD') }}"
    ansible_network_os: "f5networks.f5_bigip.bigiq"
    ansible_httpapi_use_ssl: true
    ansible_httpapi_use_proxy: false
    ansible_httpapi_validate_certs: "{{ lookup('env','F5_VALIDATE_CERTS') }}"
    ansible_httpapi_port: "{{ lookup('env','F5_SERVER_PORT') }}"
    persistent_log_messages: false
    f5_telemetry: false

  roles:
    - bigiq_regkey_pool
