---

# Test the atc_deploy module
#
# Running this playbook assumes that you have a BIG-IP installation at the
# ready to receive the commands issued in this Playbook.
#
# This module will run tests against a BIG-IP host to verify that the
# atc_deploy module behaves as expected.
#
# Usage:
#
#    ansible-playbook -i notahost, integration/bigiq_do_deploy.yaml
#
# Examples:
#
#    Run all tests on the atc_deploy module
#
#    ansible-playbook -i notahost, integration/bigiq_do_deploy.yaml
#


- name: Test the bigiq_do_deploy module
  hosts: "f5-bigiq[0]"
  connection: local
  any_errors_fatal: true

  vars:
    limit_to: '*'

  environment:
    F5_SERVER: "{{ ansible_host }}"
    F5_USER: "{{ bigiq_username }}"
    F5_PASSWORD: "{{ bigiq_password }}"
    F5_SERVER_PORT: "{{ bigiq_port }}"
    F5_VALIDATE_CERTS: "{{ validate_certs }}"

  roles:
    - bigiq_do_deploy