---
- import_tasks: setup.yaml

- name: Wait for BIG-IP to be ready, expected failure - REST
  bigip_wait:
    timeout: 10
    delay: 10
    sleep: 5
  register: result
  ignore_errors: true

- name: assert failure - REST
  assert:
    that:
      - result is not changed
      - "'greater than' in result.msg"

- name: Wait for BIG-IP to be ready, expected failure - REST
  bigip_wait:
    timeout: 15
    delay: 10
    sleep: 5
  register: result
  ignore_errors: true

- name: assert failure - REST
  assert:
    that:
      - result is not changed
      - "'greater than' in result.msg"

- name: Wait for BIG-IP to be ready, expected pass - REST
  bigip_wait:
    timeout: 25
    delay: 10
    sleep: 5
  register: result
  ignore_errors: true

- name: assert pass - REST
  assert:
    that:
      - result is not changed
